# CAPE Rightsizing — humana-claims-sql-prod
# Generated by CAPE AI Agent · Wave 1
# Projected saving: ~$370/mo · HIPAA/SOX validated

resource "azurerm_mssql_database" "claims_sql_prod" {
  name      = "humana-claims-sql-prod"
  server_id = azurerm_mssql_server.claims_primary.id

  sku_name       = "GP_S_Gen5_2"   # was: GP_S_Gen5_4
  min_capacity   = 0.5
  auto_pause_delay_in_minutes = 60  # was: -1 (disabled)

  max_size_gb = 32
  collation   = "SQL_Latin1_General_CP1_CI_AS"

  tags = {
    environment        = "production"
    business-unit      = "claims-processing"
    cost-center        = "CC-1201"
    compliance         = "hipaa,sox"
    cape-reviewed      = "true"
    cape-resized       = "wave-1-rightsizing"
  }
}
